version: '3.8'

services:
  frontend:
    build:
      context: ./ws-web
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./ws-api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=example
      - DATABASE_NAME=postgres
    depends_on:
      - db

  db:
    image: postgres:10.0-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: postgres
    ports:
      - "5433:5432" # changed host port to 5433
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:

